# This Docker Compose file was built solely for development purposes.

version: "3"
services:
  postgresql:
    environment:
      - POSTGRES_DB=ichef
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    networks:
      - pgsql-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -d ichef -h localhost -p 5432'"]
      interval: 10s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5433:80"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - pgsql-network
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3

networks:
  pgsql-network:
    driver: bridge
